// <auto-generated />
using System;
using ArizaTakipSistemi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArizaTakipSistemi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501124025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Ariza", b =>
                {
                    b.Property<int>("ArizaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArizaTanimi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("CihazId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.Property<int>("OncelikDurumu")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TahminiMaliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YapilanIslem")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("ArizaId");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Arizalar");
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Cihaz", b =>
                {
                    b.Property<int>("CihazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CihazTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriAdres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.Property<string>("SeriNumarasi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CihazId");

                    b.HasIndex("SeriNumarasi")
                        .IsUnique();

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciId = 1,
                            Ad = "Admin",
                            AktifMi = true,
                            Email = "admin@arizatakip.com",
                            OlusturulmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rol = 1,
                            Sifre = "admin123",
                            Soyad = "Yönetici",
                            Telefon = "05001234567"
                        },
                        new
                        {
                            KullaniciId = 2,
                            Ad = "Ahmet",
                            AktifMi = true,
                            Email = "ahmet@arizatakip.com",
                            OlusturulmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rol = 0,
                            Sifre = "ahmet123",
                            Soyad = "Tekniker",
                            Telefon = "05009876543"
                        });
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EskiDegerler")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.Property<int>("IslemTuru")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KayitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabloAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("YapilanIslem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("YeniDegerler")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("IslemTarihi");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TabloAdi");

                    b.ToTable("Loglar");
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Ariza", b =>
                {
                    b.HasOne("ArizaTakipSistemi.API.Models.Cihaz", "Cihaz")
                        .WithMany("Arizalar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArizaTakipSistemi.API.Models.Kullanici", "AtananTeknisyen")
                        .WithMany("AtananArizalar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AtananTeknisyen");

                    b.Navigation("Cihaz");
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Log", b =>
                {
                    b.HasOne("ArizaTakipSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany("Loglar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Cihaz", b =>
                {
                    b.Navigation("Arizalar");
                });

            modelBuilder.Entity("ArizaTakipSistemi.API.Models.Kullanici", b =>
                {
                    b.Navigation("AtananArizalar");

                    b.Navigation("Loglar");
                });
#pragma warning restore 612, 618
        }
    }
}
